### PR TITLE
Flight attendant call button for stuck puzzles

### LINKED ISSUE #218: Seal team 6
Assign roles to people
We have specific folks who jump into puzzles to get them unstuck (with specific commitments to check every puzzle every x minutes)
Should clearly make a seal barking sound when the team member enters the chat room.
Maybe a special button at top of chat "summon seal team six".

### PR DESCRIPTION
**Pull request by Torgen**
Can be triggered with the button next to the "call in" button, or with the "bot stuck" command, or by editing the status column of the blackboard (which now syncs to the "stuck" tag). Setting the tag alerts the main chat and turns the puzzle's square on the status grid yellow. Unsetting it (bot unstuck, re-press the button, etc.) notifies the chat that help is no longer sought.
Fixes #218 except for the seal noise and sorting by how long the light has been set.

### CODE REVIEW

**Comment by cscott** [comment]
I merged a version of this as ce2c4cd617fe706fbe16e5b01508108bc6c5a75c, although i hacked it to pieces (alas).
I wanted to continue to use the status field for this, and in some brainstorming during our practice hunt the "stuck puzzles team" asked for some more structured information about how exactly the puzzles were stuck.

The `isStuck` helper I added should allow compatibility between our code bases, if you want to stuck with your `stuck tag` based version.

**Comment by cscott** [comment]
I haven't merged the bot-related stuff yet; I've split that into a separate patch.  I'll squash your improvements to the help in 
0d3852c.

**Comment by Torgen** [comment]
I only used a new tag instead of status to not conflict with the test data that was already using status.

**Comment by cscott** [comment]
Since I've added structured data now, and then throw the structure away to collapse it into a text tag, it may in fact be the case that in the future I want special tags or fields for 'stuckHow', 'stuckAt', etc to allow them to be sorted.  So I may change my mind on this!  But the informal polling I did suggested that people both wanted some structure to the stuck data as well as the flexibility to add arbitrary messages in case the structured set of options don't apply.  That's been pretty much how we've been using the `status` field, so it made sense to me to first build on that... and then depending on how we end up using it in 2018 we can decide whether separate tags or some other representation makes more sense.

**Comment by cscott** [comment]
(Your patch stacks are very helpful by the way!  Even where I end up doing violence to your original patch set, it's super helpful to have a guide to what lines need to be changed, the problems encountered, etc. I get a lot out of reading a working patch.)

**Comment by cscott** [comment]
Closing this; opened #247 for the remaining bits I split off from your patch and haven't yet merged.

**Pull request closed without merging**
